CREATE TABLE IF NOT EXISTS times (
    id BIGSERIAL PRIMARY KEY,
    nome VARCHAR(45) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS jogadores (
    id BIGSERIAL PRIMARY KEY,
    nome VARCHAR(45) NOT NULL,
    idade INTEGER NOT NULL,
    time_id INTEGER DEFAULT NULL,
    FOREIGN KEY (time_id) REFERENCES times(id) ON DELETE CASCADE
);
